package platform

// GetExcludePatterns returns platform-specific exclude patterns
func getLinuxExcludes() []string {
	return []string{
		"./**/*.bin",
		"./**/*.webm",
		"./**/.build",
		"./.cache",
		"./.cargo",
		"./**/*.dll",
		"./Downloads",
		"./**/*.exe",
		"./**/*.foz",
		"./go",
		"./**/*.la",
		"./.local/share/Steam/appcache",
		"./.local/share/Steam/config",
		"./.local/share/Steam/controller_base",
		"./.local/share/Steam/depotcache",
		"./.local/share/Steam/friends",
		"./.local/share/Steam/graphics",
		"./.local/share/Steam/logs",
		"./.local/share/Steam/music",
		"./.local/share/Steam/package",
		"./.local/share/Steam/public",
		"./.local/share/Steam/resource",
		"./.local/share/Steam/shadercache",
		"./.local/share/Steam/steam",
		"./.local/share/Steam/steamapps/common",
		"./.local/share/Steam/steamui",
		"./.local/share/Steam/tenfoot",
		"./.local/share/Steam/ubuntu12_32",
		"./.local/share/Steam/ubuntu12_64",
		"./.local/share/Steam/userdata",
		"./.local/share/Trash",
		"./**/*.nls",
		"./**/node_modules",
		"./.npm",
		"./**/*.o",
		"./.rustup",
		"./snap",
		"./**/*.so",
		"./**/*.so.*",
		"./**/target",
		"./.Trash",
		"./.var/app/io.github.ungoogled_software.ungoogled_chromium",
		"./.var/app/org.mozilla.firefox",
		"./**/.venv",
		"./.vscode/extensions",
		"./**/__worktrees",
	}
}
