package platform

func getMacOSExcludes() []string {
	return []string{
		"./**/*.sock",
		"./**/*.socket",
		"./**/.build",
		"./**/.venv",
		"./**/__worktrees",
		"./**/node_modules",
		"./**/target",
		"./**/venv",
		"./.Trash",
		"./.cache/huggingface",
		"./.cache/nix",
		"./.cargo",
		"./.codeium",
		"./.cursor/extensions",
		"./.gnupg/S.*",
		"./.local/share/nvim",
		"./.npm",
		"./.ollama/models",
		"./.orbstack",
		"./.pulumi",
		"./.terraform.d",
		"./.vscode/extensions",
		"./Group Containers/HUAQ24HBR6.dev.orbstack",
		"./Library/Application Support/Chromium",
		"./Library/Application Support/Code",
		"./Library/Application Support/Cursor",
		"./Library/Application Support/FileProvider",
		"./Library/Application Support/Firefox",
		"./Library/Application Support/Google",
		"./Library/Application Support/Slack",
		"./Library/Application Support/Windsurf",
		"./Library/Application Support/rancher-desktop",
		"./Library/Application Support/virtualenv",
		"./Library/Caches",
		"./Library/Caches/CloudKit",
		"./Library/Caches/Chromium",
		"./Library/Caches/FamilyCircle",
		"./Library/Caches/Firefox",
		"./Library/Caches/Firefox/Profiles",
		"./Library/Caches/Google/Chrome",
		"./Library/Caches/com.anthropic.claudefordesktop.ShipIt",
		"./Library/Caches/com.apple.HomeKit",
		"./Library/Caches/com.apple.Safari",
		"./Library/Caches/com.apple.ap.adprivacyd",
		"./Library/Caches/com.apple.containermanagerd",
		"./Library/Caches/com.apple.homed",
		"./Library/Caches/go-build",
		"./Library/Caches/pypoetry",
		"./Library/Caches/typescript",
		"./Library/Containers",
		"./Library/Containers/com.apple.Safari",
		"./Library/Containers/com.apple.Safari.WebApp",
		"./Library/Containers/com.apple.wallpaper.extension.video",
		"./Library/Containers/com.microsoft.teams2",
		"./Library/Containers/com.utmapp.UTM",
		"./Library/Developer/Xcode",
		"./Library/Group Containers",
		"./Library/Group Containers/BJ4HAAB9B3.ZoomClient3rd",
		"./Library/Group Containers/group.com.apple.CoreSpeech",
		"./Library/Group Containers/group.com.apple.secure-control-center-preferences",
		"./Library/Mobile Documents",
		"./Library/Mobile Documents/com~apple~CloudDocs",
		"./Library/pnpm",
		"./OrbStack",
		"./Pictures",
		"./Sources/github.com/NixOS/nixpkgs",
		"./go",
		"./**/.DS_Store",
	}
}
